AppBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    lifecycleCallbacks: {  }

    oneToMany:
        events:
            targetEntity: Events
            mappedBy: user